Implement parameters for configure output of the request and response issue #41
bayne/dot-http pull request #53
Opened 2020-08-26 17:30 UTC by tglman

This is a first implementation that provide two new parameters `--request-output-format` and `--response-output-format` for now support only `%R` for the request/response line, `%H` for the headers and `%B` for the body, the options are case sensitive.

The "escaped characters" like `\n` it often depend on the shell, I still need to investigate how to support them properly any suggestion is welcome.

also I put there two options one for request and one for response, because also print computed informations of the request can be useful, feedback on this is also welcome.

Regards

2020-10-16 00:20 UTC, bayne requested changes
This looks great! A couple tweaks and we should be good to go. Thanks again

2020-10-16 00:20 UTC, bayne commented on src/output/tests.rs
> +}
Could we add another test for verifying the behaviour we wanted with https://github.com/bayne/dot-http/issues/41? (only output body)

2020-10-16 00:20 UTC, bayne commented on src/main.rs
> +                .default_value("%R\n%H\n%B\n")
Can you escape the `\n`? The help information looks a bit off.

2020-10-16 00:20 UTC, bayne commented on src/main.rs
> +                .default_value("%R\n\n")
Same here, these need to be escaped

2020-10-16 00:20 UTC, bayne commented on src/main.rs
> +                .long("response-output-format")
Let's make this one `-s`
```suggestion
                .long("response-output-format")
                .short("s")
```

2020-10-16 00:20 UTC, bayne commented on src/main.rs
> +                .long("request-output-format")
And this one `-q`
```suggestion
                .long("request-output-format")
                .short("q")
```

2020-10-17 10:17 UTC, tglman commented
Hi,

Mad the changes, I could not escape directly the default value, because it was actually the default value, added it by hand in the help message

2020-10-17 19:14 UTC, merged